import { createHash } from "node:crypto";
import { canonicalJson } from "../src/runtime/manifest-loader";
import type { FrontendManifest, RoleFrontendManifest } from "../src/runtime/contracts";

export function fixtureManifest(): FrontendManifest {
  const base = { version: 1 as const, target_frappe_major: 16 as const, project: "task_tracker", label: "Task Tracker", spec_hash: "a".repeat(64), roles: [{ role: "Task User", entities: [{ name: "task", doctype: "Task", label: "Task", description: "", fields: [{ name: "title", label: "Title", field_type: "Data", required: true, unique: false, default: null, description: "", component: "text-input", visible: true as const, read_only: false, select_options: [], link_target_entity: null, link_target: null, creatable: true, editable: true }], actions: { read: true, create: true, write: true, delete: false } }], routes: [{ id: "task_list", kind: "list" as const, entity: "task", label: "Tasks", path: "/task_tracker/task", fields: ["title"], allowed_filters: [{ name: "title", field_type: "Data", operators: ["equals", "contains"] }], allowed_orders: ["title:asc", "title:desc"], record_id_field: "name" as const }, { id: "task_form", kind: "form" as const, entity: "task", label: "Task", path: "/task_tracker/task/:name", fields: ["title"], allowed_filters: [], allowed_orders: [], record_id_field: "name" as const }], navigation: [{ id: "task_list", label: "Tasks", entity: "task", route_id: "task_list", path: "/task_tracker/task" }] }] };
  return { ...base, manifest_hash: createHash("sha256").update(canonicalJson(base)).digest("hex") };
}

export function linkRole(): RoleFrontendManifest {
  const project = { name: "project", doctype: "Project", label: "Project", description: "", fields: [{ name: "title", label: "Title", field_type: "Data", required: true, unique: false, default: null, description: "", component: "text-input", visible: true as const, read_only: false, select_options: [], link_target_entity: null, link_target: null, creatable: true, editable: true }], actions: { read: true, create: true, write: true, delete: true } };
  const task = { name: "task", doctype: "Task", label: "Task", description: "", fields: [{ name: "project", label: "Project", field_type: "Link", required: true, unique: false, default: null, description: "", component: "link-autocomplete", visible: true as const, read_only: false, select_options: [], link_target_entity: "project", link_target: "Project", creatable: true, editable: true }], actions: { read: true, create: true, write: true, delete: true } };
  return { role: "Task Manager", entities: [task, project], routes: [{ id: "task_form", kind: "form", entity: "task", label: "Task", path: "/task_tracker/task/:name", fields: ["project"], allowed_filters: [], allowed_orders: [], record_id_field: "name" }, { id: "project_list", kind: "list", entity: "project", label: "Projects", path: "/task_tracker/project", fields: ["title"], allowed_filters: [{ name: "title", field_type: "Data", operators: ["equals", "contains"] }], allowed_orders: ["title:asc"], record_id_field: "name" }], navigation: [] };
}
