<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import FieldControl from "../components/FieldControl.vue";
import LinkAutocomplete from "../components/LinkAutocomplete.vue";
import type { EntityManifest, FrontendField, FrontendRoute, RoleFrontendManifest } from "../runtime/contracts";
import { resolveLinkBinding, type LinkBinding } from "../runtime/link-autocomplete";
import { createResourceClient, ResourceRequestError, type ResourceClient } from "../runtime/resource-api";
import { isDirty, makeDraft, mutationFields, mutationPayload, type RecordMode, validateDraft } from "../runtime/record-draft";
const props = defineProps<{ entity: EntityManifest; route: FrontendRoute; role: RoleFrontendManifest; name?: string; client: ResourceClient }>();
const emit = defineEmits<{ saved: [name: string]; deleted: [name: string]; cancel: [] }>();
const mode: RecordMode = props.name ? "edit" : "create"; const fields = mutationFields(props.entity, props.route, mode); const values = reactive<Record<string, unknown>>(makeDraft(props.entity, props.route, mode)); const initial = ref<Record<string, unknown>>({ ...values }); const loading = ref(Boolean(props.name)); const saving = ref(false); const deleting = ref(false); const confirmingDelete = ref(false); const error = ref<string | null>(null); const errors = ref<Record<string, string>>({}); const dirty = computed(() => isDirty(initial.value, values));
onMounted(async () => { if (!props.name) return; try { const result = await props.client.read(props.name); const record = (result as { data?: Record<string, unknown> }).data ?? {}; const draft = makeDraft(props.entity, props.route, mode, record); Object.assign(values, draft); initial.value = { ...draft }; } catch (cause) { error.value = cause instanceof Error ? cause.message : "Unable to load record"; } finally { loading.value = false; } });
async function save() { errors.value = validateDraft(fields, values); if (Object.keys(errors.value).length) return; saving.value = true; error.value = null; try { const result = mode === "create" ? await props.client.create(mutationPayload(fields, values)) : await props.client.update(props.name!, mutationPayload(fields, values)); const name = (result as { data?: { name?: unknown } }).data?.name; initial.value = { ...values }; emit("saved", typeof name === "string" ? name : props.name ?? ""); } catch (cause) { error.value = cause instanceof Error ? cause.message : "Unable to save record"; if (cause instanceof ResourceRequestError) errors.value = { ...errors.value, ...cause.fieldErrors }; } finally { saving.value = false; } }
function linkBinding(field: FrontendField): LinkBinding | null { try { return resolveLinkBinding(props.role, field); } catch { return null; } }
function linkClient(binding: LinkBinding): ResourceClient { return binding.entity.name === props.entity.name ? props.client : createResourceClient(binding.entity, undefined, { requireCsrf: true }); }
async function remove() { if (!props.name || !props.entity.actions.delete) return; deleting.value = true; error.value = null; try { await props.client.delete(props.name); emit("deleted", props.name); } catch (cause) { error.value = cause instanceof Error ? cause.message : "Unable to delete record"; } finally { deleting.value = false; confirmingDelete.value = false; } }
</script>
<template><section><h1>{{ route.label }}</h1><p v-if="loading">Loading…</p><form v-else @submit.prevent="save"><p v-if="error" role="alert">{{ error }}</p><template v-for="field in fields" :key="field.name"><LinkAutocomplete v-if="field.component === 'link-autocomplete' && linkBinding(field)" v-model="values[field.name]" :binding="linkBinding(field)!" :client="linkClient(linkBinding(field)!)" :disabled="saving || deleting" :error="errors[field.name]" /><FieldControl v-else v-model="values[field.name]" :field="field" :disabled="saving || deleting" :error="errors[field.name]" /></template><p v-if="dirty">Unsaved changes</p><button type="submit" :disabled="saving || deleting">{{ saving ? "Saving…" : "Save" }}</button><button v-if="mode === 'edit' && entity.actions.delete" type="button" :disabled="saving || deleting" @click="confirmingDelete = true">Delete</button><button type="button" :disabled="saving || deleting" @click="emit('cancel')">Cancel</button><section v-if="confirmingDelete" role="alertdialog" aria-label="Confirm deletion"><p>Delete this {{ entity.label }}? This cannot be undone.</p><button type="button" :disabled="deleting" @click="remove">{{ deleting ? "Deleting…" : "Confirm delete" }}</button><button type="button" :disabled="deleting" @click="confirmingDelete = false">Keep record</button></section></form></section></template>
